camel:
  springboot:
    # The Camel context name
    name: CamelRestSql

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true


# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

  
keycloak:
 realm: temasek-demo
 resource: temasek-demo-client
 ssl-required: none
 bearer-only: true
 realm-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm8K+ZLbT2791FiBDCpATkQc6lOyC7VfxqoGnCsJtIl+KHCKHWexaxrvnj9DMIN+DcuCwAAJw7K6OPQWcbosLZYHWB7RpWmbdN3Mmgt6TMfP3CSvYDwlX5xHFBoeJXDT9HWtYJNC0yfDhDW4RjXCcffGjBYRlX3NUlaPhBDxjt2xfuwoI6xN1UNXwBMUknoy/7hXZibX8X8+V0mU4+MdBfcCZznAQ8OsX0qHXCIkQxl5I4TjkBdlM9zpKAaxU+CdkBkH1hBQcZL+ZO/6xkMEuQ8mrhpre+EXlkGh250KZBSRNtPnzNGM83qJnzMNnPf4rLH3I3TsM3NV91SSoLkMNmQIDAQAB
 principal-attribute: preferred_username	
 securityConstraints:
  - authRoles: 
     - demo
    securityCollections:
     - name: demo resource
       patterns:
        - /demos